[tools]
eza = "latest"
fd = "latest"
fzf = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
opencode = "latest"
pnpm = "latest"
python = "latest"
ripgrep = "latest"
ruff = "latest"
rust = "latest"
starship = "latest"
typst = "latest"
usage = "latest"
uv = "latest"
zig = "latest"
codex = "latest"
gh = "latest"

[env]
EDITOR = "nvim"
BROWSER = "explorer.exe"
XDG_CONFIG_HOME = "{{ get_env(name='HOME', default=env.USERPROFILE) }}/.config"

[settings]
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[settings.npm]
package_manager = "pnpm"

[tasks.gituseriniad]
run = [
    "git config user.name 's1f10230101'",
    "git config user.email 's1f102301011@iniad.org'"
    ]
dir = "{{cwd}}"

[tasks.gituserhiroki]
run = [
    "git config user.name 'hiroki706'",
    "git config user.email 'hiroki.okubo.tokyo@gmail.com'"
    ]
dir = "{{cwd}}"

